#!/bin/sh
#
# Use this to compile CoffeeScript into JS
coffee --map --compile --output build/ src/counter.coffee
coffee --bare --compile --output build/spec src/spec
echo CoffeeScript compiled successfully